### ISSUE TITLE
Doesn't work in Django 1.8

### ISSUE THREAD

**Issue by puretekniq** [WoLpH/django-tags-input#6]
'Manager' object has no attribute 'get_query_set'

tags_input/admin.py in formfield_for_manytomany, line 17

Obviously the problem of them renaming get_query_set to get_queryset.  Any chance that this will be fixed?

**Comment by WoLpH** [comment]
Should be fairly trivial to fix, I should have some time to work on it next
week :)

**Comment by WoLpH** [comment]
I've just pushed 2.0.1 to pypi: https://pypi.python.org/pypi/django-tags-input
